FROM node:20.11.1-alpine AS builder
WORKDIR /app
COPY . .
RUN npm ci && npm run build

FROM node:20.11.1-alpine AS runner
WORKDIR /app
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/package*.json ./
RUN npm ci --only=production
CMD ["node", "dist/index.js"]
