name: Trigger Notification Worker

on:
  schedule:
    - cron: '*/8 * * * *'
  workflow_dispatch:

jobs:
  call-worker-api:
    runs-on: ubuntu-latest

    steps:
      - name: Debug Print request URL
        run: echo "Calling to api"
        env:
          WORKER_URL: ${{ secrets.WORKER_URL }}
          CRON_SECRET: ${{ secrets.CRON_SECRET }}
        
      - name: Make GET request to worker API
        run: curl -v "${secrets.WORKER_URL}?token=${secrets.CRON_SECRET}"
        env:
          WORKER_URL: ${{ secrets.WORKER_URL }}
          CRON_SECRET: ${{ secrets.CRON_SECRET }}
