name: Trigger Notification Worker

on:
  schedule:
    - cron: '*/8 * * * *'
  workflow_dispatch:

jobs:
  call-worker-api:
    runs-on: ubuntu-latest

    steps:
      - name: Make GET request to worker API
        run: echo "Calling to ${secrets.WORKER_URL}?token=${secrets.CRON_SECRET}"
        
      - name: Debug Print request URL
        run: curl -v "${secrets.WORKER_URL}?token=${secrets.CRON_SECRET}"
